users:
  - name: user
    groups: sudo
    shell: /bun/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICysionz7EgNY6uosAtfh7e/kwcflnPR5+18k4KIw89d user@Ubuntu-netology-1